### ISSUE TITLE
Choice Chips is not selectable

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-catalog#214] opened 2018-10-02 01:15 UTC
<img width="610" alt="screen shot 2018-10-01 at 18 14 39" src="https://user-images.githubusercontent.com/579873/46323986-f4ac2c00-c5a5-11e8-9cad-a03667ddc5bc.png">

Choice chips isn't selectable

**Comment by kfranqueiro** [comment] 2018-10-02 12:44
Duplicate of #176

**Closed by kfranqueiro** 2018-10-02 12:44 UTC
